default:
  tags:
    - docker
    - ubuntu

  image: "nexus.nic.etu:8181/nic/fedora_33:base"

stages:
  - test

unit_tests:
  stage: test
  script:
    - dnf update -y && dnf install -y python3 python3-pip protobuf-compiler
    - pip3 install -r requirements.txt
    - python3 setup.py build
    - python3 -m unittest discover tests